### ISSUE TITLE
Sometimes colors don't work

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#815] opened 2022-11-01 17:43 UTC
**Describe the bug**
Rarely, upon launching the game, none of the color-styling shows up.
This causes grass in the map to be gray instead of green, and dialog buttons to have no highlighting.

**To Reproduce**
This has happened perhaps in 1/100 launches of the game (at least twice for me, so far).
Last time it happened, I had passed both the `--scenario` and `--run` options.

    stack run -- --scenario my-scenario.yaml --run my-script.sw

The contents of `my-script.sw` were as follows:
```
def plod = move; end

def rotate = turn left; end;

plod; rotate; plod;
```
Note the absence of the semicolon on the first line, if that may be relevant.  The program still ran, though.
The failure is nondeterministic; I ran it one time, and got no colors.  I quit and ran it again with no changes, and the colors were back.

**Expected behavior**
Normal coloring.

**Screenshots**
| Normal | Failure mode |
| --- | --- |
| ![Screenshot from 2022-11-01 10-38-26](https://user-images.githubusercontent.com/261693/199301506-d94e4f54-39cf-4e51-af85-792517fe13d6.png) | ![Screenshot from 2022-11-01 10-37-55](https://user-images.githubusercontent.com/261693/199301476-1bf58901-7d7f-4454-91f5-30c504aec23d.png) |

**Additional context**
Version: commit `1d928810`.

**Comment by byorgey** [comment] 2022-11-01 19:30
I have also experienced this.  I have not noticed any patterns in terms of when it happens.

**Comment by xsebek** [comment] 2022-11-01 21:13
Maybe it is a brick issue, since we do not add any custom logic to determine the TERM capabilities?

**Comment by xsebek** [comment] 2022-11-05 12:29
@kostmo @byorgey how do we want to solve this issue? I am unable to reproduce it - I tried:
- repeatedly opening the released Swarm binary from the shell in a cycle
- same for cabal binary

We can:
1. close this as unreproducible
2. report it at Brick and ask if someone else encountered the same problem
3. force Swarm to use colours and maybe add some flag to turn it on/off

**Comment by byorgey** [comment] 2022-11-05 13:05
I think we should at least do option (2), doesn't hurt to ask.  Re: (3), what do you mean by "force Swarm to use colours"?  How would we do that?

**Comment by xsebek** [comment] 2022-11-05 14:07
@byorgey by setting Vty options when starting Swarm.

I have not digged into the documentation, but I am fairly certain we can edit the result of `buildVty` (I think it is called) that we use currently.

**Comment by byorgey** [comment] 2022-11-05 14:31
I see, interesting.  That might be worth trying.

**Comment by xsebek** [comment] 2022-11-11 21:28
This just happened to me:
![image](https://user-images.githubusercontent.com/44544735/201431643-47021cca-7852-46f4-93e0-eb9c65f21cd1.png)

It happened after the previous run crashed, but I could not reproduce it afterwards. :disappointed:

**Comment by kostmo** [comment] 2022-11-11 21:58
> This just happened to me

Were you running with any particular CLI options, or just with `stack run`?

**Comment by xsebek** [comment] 2022-11-11 22:04
@kostmo just the released `swarm` that I installed with `cabal install swarm-0.2.0.0`.

**Comment by kostmo** [comment] 2022-11-11 22:07
Ok, I had a theory that `--run`-ing a script may have been a cause.  Seems that's been eliminated.

**Comment by byorgey** [comment] 2022-11-11 22:32
I did option (2), see the above linked upstream issue.

**Closed** 2022-11-11 23:44 UTC
Labels: Bug, T-UI
