### ISSUE TITLE
Immediate freeze upon launching most scenarios

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1000] opened 2023-01-10 23:19 UTC
Starting scnenarios through the menu or through the command line with `--scenario` causes the program to freeze.  `pkill swarm` must be executed in the terminal to recover.  E.g. this one freezes:

    stack run -- --scenario data/scenarios/creative.yaml

It seems that not all scenarios freeze, however; these ones work:

    stack run -- --scenario data/scenarios/Tutorials/scan.yaml
    stack run -- --scenario data/scenarios/Challenges/2048.yaml

**Comment by byorgey** [comment] 2023-01-10 23:20
Issue 1000!  @kostmo is the winner! :tada:

**Comment by byorgey** [comment] 2023-01-10 23:23
Is this on the current `main` branch?  I can't reproduce this.

**Comment by kostmo** [comment] 2023-01-10 23:50
Observed at commit 68c992aa on the main branch.  Tried the following without success:

* `stack clean`
* `git clean -fdx`
* Reboot computer

It seems that the freeze is not absolute; if I wait long enough, the world UI will display, but will then still be unresponsive to keyboard input.

**Comment by byorgey** [comment] 2023-01-10 23:56
I still cannot reproduce.  Maybe some of your data/save/history files got corrupted or huge somehow, and swarm is taking a very long time trying to read/process it somehow?

**Comment by kostmo** [comment] 2023-01-11 06:02
In case it is relevant, here's what I encountered before the freeze issue:
```
kostmo@dell-ubuntu:~/github/swarm$ stack run
Warning: while processing Tutorials/00-ORDER.txt: files not listed in 00-ORDER.txt will be ignored
  - install.yaml
Failed to load scenarios: Aeson exception:
Error in $.solution: Could not parse term: 1: Unbound variable install
kostmo@dell-ubuntu:~/github/swarm$ find -name install.yaml
./.stack-work/install/x86_64-linux-tinfo6/3598b35d16175b2123168d7c37dbbc360ad9ba49ad215feda9c6c5d30c8c8528/9.2.5/share/x86_64-linux-ghc-9.2.5/swarm-0.2.0.0/scenarios/Tutorials/install.yaml
kostmo@dell-ubuntu:~/github/swarm$ git clean -fdx
Removing .hie/
Removing .stack-work/
Removing stack.yaml.lock
kostmo@dell-ubuntu:~/github/swarm$ find -name install.yaml
kostmo@dell-ubuntu:~/github/swarm$
```

I have since nuked the `.local/share/swarm` directory, but am still hitting the freeze issue.

**Comment by kostmo** [comment] 2023-01-11 08:05
Ok, I've pinpointed the problem to commit 3087021 (#975).  The parent commit (dd28529) does not exhibit the problem.

**Comment by kostmo** [comment] 2023-01-11 08:58
I've reproduced the problem on two different machines, with Ubuntu 21.10 and 22.04.1.

**Comment by byorgey** [comment] 2023-01-11 11:49
I was finally able to reproduce this.  Strangely, it seems turning off optimizations with `--fast` (`stack build --fast && stack exec swarm ...` ) makes the freeze go away.  Note that I normally build with `--fast` because it makes compilation much faster and has never seemed to affect the speed of the resulting executable in any way, which is why I was initially unable to reproduce.  @xsebek , have you encountered this?  What options do you use when building with `cabal`?

**Comment by byorgey** [comment] 2023-01-11 11:52
The warning about `install.yaml` and parse error is not relevant, that's due to the `stack` bug where it doesn't clean out the directory holding data files.  That often happens to me when switching branches, the only solution is to `stack clean --full` (or just `rm -rf .stack-work`) and rebuild.

**Comment by xsebek** [comment] 2023-01-11 13:19
I encountered it too, with the default Cabal options and GHC 9.2.5.

No idea what is going on there, it can’t be the game logic because that would have effected integration tests. 🤔

The only times I remember the game freezing were:
- in ranching/GoL scenarios with a lot of busy robots
- when opening modals with absurdly long list of widgets (messages and that bug with space under help)

But this happened to me opening Creative scenario that has no robots and no big lists in TUI. 🤔

**Comment by xsebek** [comment] 2023-01-11 13:27
I wonder if this is somehow caused by the map consisting of a lot of one character widgets.

Its hard to tell without any per-function performance measurements. 😕

**Comment by ccasin** [comment] 2023-03-16 19:49
For what it's worth, I initially installed swarm from hackage using whatever ghc I had lying around, which turned out to be 9.2.5.  I thought the game just had really long load times, and found this issue when I went to see if there were any about improving that or adding some kind of load screen :)

I subsequently updated to 9.6.1, only to find out its `base` was too new for the swarm in hackage, and then downgraded to 9.4.4, which does work and produce a swarm without the freeze issue.  Perhaps putting a warning about 9.2.5 in the installation instructions until this issue is resolved would be wise?

**Comment by byorgey** [comment] 2023-03-17 02:41
Good idea!

**Comment by byorgey** [comment] 2024-01-26 23:02
I'm going to close this.  The freeze has not been observed on any more recent versions of GHC; we now support GHC 9.4 and 9.6 and will probably support 9.8 soon.  There have also been more point releases in the 9.2.x series, and I can confirm that GHC 9.2.7 does not seem to have this bug.

**Closed by byorgey** 2024-01-26 23:02 UTC
Labels: Bug, S-Critical
