### ISSUE TITLE
Add swap command

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#684] opened 2022-09-14 20:59 UTC
When writing robot programs it is easy to get into race conditions.

Consider this simplified example from #669:
- robot A at (1,1) watches location (2,3) and if it has an entity "three" it will grab and place
- robot B at (2,3) watches location (1,1) and if it is empty it will grab and place "two" otherwise "three"

The worst part is that in extended programs race conditions rarely happen because robots will spend some ticks not looking.

Adding an atomic `swap` command that works like `a <- grab; place e; return a` would solve these issues.

**Comment by byorgey** [comment] 2022-09-14 21:11
This is a duplicate of #680. :smile:

**Comment by xsebek** [comment] 2022-09-14 21:19
Sounds like closing two issues at once to me. :laughing:

**Closed** 2022-09-17 11:21 UTC
Labels: Z-Feature, L-Language design
